{{- if .Values.vault_settings.aws_secret_manager }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.csi.csi_default_name }}
spec:
  provider: aws
  parameters:
    region: {{ .Values.vault_settings.aws_secret_manager_region }}
    objects: |
      - objectName: "tlscrt"
        objectType: "secretsmanager"
        objectVersionLabel: "AWSCURRENT"
      - objectName: "tlskey"
        objectType: "secretsmanager"
        objectVersionLabel: "AWSCURRENT"
      - objectName: "upstream-auth-url"
        objectType: "secretsmanager"
        objectVersionLabel: "AWSCURRENT"
      - objectName: "csp-permitted-origin"
        objectType: "secretsmanager"
        objectVersionLabel: "AWSCURRENT"
      - objectName: "auth-uri"
        objectType: "secretsmanager"
        objectVersionLabel: "AWSCURRENT"
      - objectName: "auth-enabled"
        objectType: "secretsmanager"
        objectVersionLabel: "AWSCURRENT"
      - objectName: "feature-document-upload"
        objectType: "secretsmanager"
        objectVersionLabel: "AWSCURRENT"
      - objectName: "feature-document-delete"
        objectType: "secretsmanager"
        objectVersionLabel: "AWSCURRENT"
      - objectName: "feature-model-management"
        objectType: "secretsmanager"
        objectVersionLabel: "AWSCURRENT"
      - objectName: "feature-document-change-type"
        objectType: "secretsmanager"
        objectVersionLabel: "AWSCURRENT"
      - objectName: "feature-run-pipeline"
        objectType: "secretsmanager"
        objectVersionLabel: "AWSCURRENT"
  secretObjects:
    - secretName: {{ .Values.secrets.deps_nginx.secretName }}
      type: Opaque
      data:
        - objectName: "feature-document-upload"
          key: feature-document-upload
        - objectName: "feature-document-delete"
          key: feature-document-delete
        - objectName: "feature-model-management"
          key: feature-model-management
        - objectName: "feature-document-change-type"
          key: feature-document-change-type
        - objectName: "feature-run-pipeline"
          key: feature-run-pipeline
        - objectName: "tlscrt"
          key: tls.crt
        - objectName: "tlskey"
          key: tls.key
        - objectName: "upstream-auth-url"
          key: upstream-auth-url
        - objectName: "csp-permitted-origin"
          key: csp-permitted-origin
        - objectName: "auth-uri"
          key: auth-uri
        - objectName: "auth-enabled"
          key: auth-enabled
{{- end }}