{{- if .Values.vault_settings.hashicorp_vault }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.csi.csi_default_name }}
spec:
  provider: vault
  secretObjects:
  - data:
    - key: certificate
      objectName: certificate
    - key: certificate-key
      objectName: certificate-key
    - key: upstream-auth-url
      objectName: upstream-auth-url
    - key: csp-permitted-origin
      objectName: csp-permitted-origin
    - key: auth-uri
      objectName: auth-uri
    - key: auth-enabled
      objectName: auth-enabled
    - key: feature-document-upload
      objectName: feature-document-upload
    - key: feature-document-delete
      objectName: feature-document-delete
    - key: feature-model-management
      objectName: feature-model-management
    - key: feature-document-change-type
      objectName: feature-document-change-type
    - key: feature-run-pipeline
      objectName: feature-run-pipeline          
    secretName: {{ .Values.secrets.deps_nginx.secretName }}
    type: Opaque
  parameters:
    roleName: {{ .Values.csi.roleName }}
    vaultAddress: "https://vault_host"
    vaultNamespace: "vault_namespace"
    vaultKubernetesMountPath: {{ .Values.csi.vaultKubernetesMountPath }}
    vaultSkipTLSVerify: "true"
    # vaultCACertPath: ""
    objects: |
      - objectName: "feature-document-upload"
        secretPath: "{{ .Values.csi.vault_namespace }}/data/feature-flags"
        secretKey: "feature-document-upload"

      - objectName: "feature-document-delete"
        secretPath: "{{ .Values.csi.vault_namespace }}/data/feature-flags"
        secretKey: "feature-document-delete"

      - objectName: "feature-model-management"
        secretPath: "{{ .Values.csi.vault_namespace }}/data/feature-flags"
        secretKey: "feature-model-management"

      - objectName: "feature-document-change-type"
        secretPath: "{{ .Values.csi.vault_namespace }}/data/feature-flags"
        secretKey: "feature-document-change-type"

      - objectName: "feature-run-pipeline"
        secretPath: "{{ .Values.csi.vault_namespace }}/data/feature-flags"
        secretKey: "feature-run-pipeline"

      - objectName: "certificate"
        secretPath: "{{ .Values.csi.vault_namespace }}/data/deps-nginx/nginx-ssl-certificate"
        secretKey: "certificate"

      - objectName: "certificate-key"
        secretPath: "{{ .Values.csi.vault_namespace }}/data/deps-nginx/nginx-ssl-certificate"
        secretKey: "certificate-key"

      - objectName: "upstream-auth-url"
        secretPath: "{{ .Values.csi.vault_namespace }}/data/deps-nginx/upstream-auth-url"
        secretKey: "upstream-auth-url"

      - objectName: "csp-permitted-origin"
        secretPath: "{{ .Values.csi.vault_namespace }}/data/deps-nginx/csp-permitted-origin"
        secretKey: "csp-permitted-origin"

      - objectName: "auth-uri"
        secretPath: "{{ .Values.csi.vault_namespace }}/data/deps-nginx/auth-uri"
        secretKey: "auth-uri"
      
      - objectName: "auth-enabled"
        secretPath: "{{ .Values.csi.vault_namespace }}/data/common-secret"
        secretKey: "auth-enabled"
{{- end }}
