{{- if .Values.vault_settings.gcp_secret_manager }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.csi.csi_default_name }}
spec:
  provider: gcp
  parameters:
    secrets: |
      - resourceName: "projects/{{ .Values.secret_project_id.id }}/secrets/feature-document-upload/versions/latest" 
        fileName: "feature-document-upload"
      - resourceName: "projects/{{ .Values.secret_project_id.id }}/secrets/feature-document-delete/versions/latest" 
        fileName: "feature-document-delete"
      - resourceName: "projects/{{ .Values.secret_project_id.id }}/secrets/feature-model-management/versions/latest" 
        fileName: "feature-model-management"
      - resourceName: "projects/{{ .Values.secret_project_id.id }}/secrets/feature-document-change-type/versions/latest" 
        fileName: "feature-document-change-type"
      - resourceName: "projects/{{ .Values.secret_project_id.id }}/secrets/feature-run-pipeline/versions/latest" 
        fileName: "feature-run-pipeline"
      - resourceName: "projects/{{ .Values.secret_project_id.id }}/secrets/upstream-auth-url/versions/latest" 
        fileName: "upstream-auth-url"
      - resourceName: "projects/{{ .Values.secret_project_id.id }}/secrets/auth-enabled/versions/latest" 
        fileName: "auth-enabled"
      - resourceName: "projects/{{ .Values.secret_project_id.id }}/secrets/csp-permitted-origin/versions/latest" 
        fileName: "csp-permitted-origin"
      - resourceName: "projects/{{ .Values.secret_project_id.id }}/secrets/auth-uri/versions/latest" 
        fileName: "auth-uri"
      - resourceName: "projects/{{ .Values.secret_project_id.id }}/secrets/tlscrt/versions/latest" 
        fileName: "tls.crt"
      - resourceName: "projects/{{ .Values.secret_project_id.id }}/secrets/tlskey/versions/latest" 
        fileName: "tls.key"
  secretObjects:
    - secretName: {{ .Values.secrets.deps_nginx.secretName }}
      type: Opaque
      data:
      - objectName: "tls.key"
        key: tls.key
      - objectName: "tls.crt"
        key: tls.crt
      - objectName: "auth-uri"
        key: auth-uri
      - objectName: "csp-permitted-origin"
        key: csp-permitted-origin
      - objectName: "auth-enabled"
        key: auth-enabled
      - objectName: "upstream-auth-url"
        key: upstream-auth-url
      - objectName: "feature-run-pipeline"
        key: feature-run-pipeline
      - objectName: "feature-document-change-type"
        key: feature-document-change-type
      - objectName: "feature-model-management"
        key: feature-model-management
      - objectName: "feature-document-delete"
        key: feature-document-delete
      - objectName: "feature-document-upload"
        key: feature-document-upload
{{- end }}
