apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    {{- include "deps-nginx.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "deps-nginx.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "deps-nginx.selectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets }}
      {{- end }}
      {{- if or .Values.vault_settings.hashicorp_vault .Values.vault_settings.gcp_secret_manager .Values.vault_settings.aws_secret_manager }}
      serviceAccountName: {{ .Values.service_account.serviceAccountName }}
      {{- end }}
      containers:
        {{- if .Values.include_dns.enabled }}
        - args:
          - --listen
          - "127.0.0.11:53"
          - --default-resolver
          - --append-search-domains
          image: '{{ .Values.registry }}{{ .Values.dnsmasq_image.path }}:{{ .Values.dnsmasq_image.tag }}'
          imagePullPolicy: {{ .Values.dnsmasq_image.pullPolicy }}
          name: dnsmasq
        {{- end }}
        - name: {{ .Chart.Name }}
          image: '{{ .Values.registry }}{{ .Values.image.path }}:{{ .Values.image.tag | default "latest" }}'
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              {{ if .Values.nginx_settings.SSL.enabled }}
              containerPort: {{ .Values.nginx_settings.NGINX_PORT }}
              {{ else }}
              containerPort: {{ .Values.nginx_settings.NGINX_UNSECURE_PORT }}
              {{ end }}
              protocol: TCP
          envFrom:
          - configMapRef:
              name: nginx-configmap
              optional: false
          env:
          {{- if .Values.vault_settings.enabled }}
          {{- toYaml .Values.vault_enabled.env | nindent 10 }}
          {{ else }}
          {{- toYaml .Values.vault_disabled.env | nindent 10 }}
          {{- end }}

          volumeMounts:
          {{- if .Values.vault_settings.enabled }}
          - name: secrets-store-inline
            mountPath: {{ .Values.secrets_location.secrets_default_path }}
            readOnly: true
          {{- end }}
          {{ if .Values.nginx_settings.HEALTHCHECK.enabled }}
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            failureThreshold: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            failureThreshold: 10
            timeoutSeconds: 5
          {{ end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
      {{- if .Values.vault_settings.enabled }}
      - name: secrets-store-inline
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: {{ .Values.csi.csi_default_name }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
