{{- if .Values.ingress.redirect_to_https }}
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: documentation-replace
spec:
  redirectRegex:
    regex: "^https://{{ .Values.ingress.host }}/documentation$"
    replacement: "https://{{ .Values.ingress.host }}/documentation/"
    permanent: true
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: documentation
spec:
  stripPrefix:
    forceSlash: false
    prefixes:
      - /documentation
{{ end }}
