{{- if .Values.ingress_route.enabled -}}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Values.ingress_route.name }}
  namespace: {{ .Values.ingress_route.namespace }}
spec:
  entryPoints:
    - websecure
  routes:
  - kind: Rule
    match: Host(`{{ .Values.ingress_route.host }}`) && PathPrefix (`/rabbitmq`)
    services:
    - kind: Service
      name: {{ .Values.ingress_route.serviceRabbitmq }}
      namespace: {{ .Values.ingress_route.namespace }}
      port: 15672
  - kind: Rule
    match: Host(`{{ .Values.ingress_route.host }}`)
    services:
    - kind: Service
      name: {{ .Values.ingress_route.serviceNginx }}
      namespace: {{ .Values.ingress_route.namespace }}
      port: 443
  tls:
    secretName: {{ .Values.ingress_route.secretName }}
    options:
      name: {{ .Values.ingress_route.nameOption }}
      namespace: {{ .Values.ingress_route.namespace }}
---
apiVersion: traefik.containo.us/v1alpha1
kind: TLSOption
metadata:
  name: {{ .Values.ingress_route.nameOption }}
  namespace: {{ .Values.ingress_route.namespace }}
spec:
  minVersion: {{ .Values.ingress_route.minVersion }}
  maxVersion: {{ .Values.ingress_route.maxVersion }}
  curvePreferences:
    - CurveP521
    - CurveP384
  cipherSuites:
    - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
    - TLS_RSA_WITH_AES_256_GCM_SHA384

{{- end }}
