{{- if .Values.ingress.enabled -}}
{{- $fullName := include "deps-nginx.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "deps-nginx.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
    {{- if and .Values.ingress.redirect_to_https .Values.ingress.comparison }}
    traefik.ingress.kubernetes.io/router.middlewares: {{ .Release.Namespace }}-redirect-https@kubernetescrd, {{ .Release.Namespace }}-frontend-comparison@kubernetescrd, {{ .Release.Namespace }}-documentation-replace@kubernetescrd, {{ .Release.Namespace }}-documentation@kubernetescrd
    {{- else if .Values.ingress.redirect_to_https }}
    traefik.ingress.kubernetes.io/router.middlewares: {{ .Release.Namespace }}-redirect-https@kubernetescrd, {{ .Release.Namespace }}-documentation-replace@kubernetescrd, {{ .Release.Namespace }}-documentation@kubernetescrd
    {{- else if .Values.ingress.comparison }}
    traefik.ingress.kubernetes.io/router.middlewares: {{ .Release.Namespace }}-frontend-comparison@kubernetescrd, {{ .Release.Namespace }}-documentation-replace@kubernetescrd, {{ .Release.Namespace }}-documentation@kubernetescrd
    {{- end }}
spec:
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - backend:
              service:
                name: rabbitmq
                port:
                  number: 15672
            path: /rabbit
            pathType: Prefix
          - backend:
              service:
                name: documentation
                port:
                  number: 8000
            path: /documentation
            pathType: Prefix
          - backend:
              service:
                name: nginx
                port:
                  number: 443
            path: /
            pathType: Prefix
    {{- if .Values.ingress.hostlabelingtool }}
    - host: {{ .Values.ingress.hostlabelingtool }}
      http:
        paths:
          - backend:
              service:
                name: labeling-tool
                port:
                  number: 8077
            path: /
            pathType: Prefix
    {{- end }}
    {{- if .Values.ingress.frontendcustomization }}    
    - host: {{ .Values.ingress.frontendcustomization }}
      http:
        paths:
        {{- if .Values.ingress.comparison }}
          - backend:
              service:
                name: deps-frontend-comparison
                port:
                  number: 8000
            path: /comparison
            pathType: Prefix
        {{- end }}     
          - backend:
              service:
                name: frontend-customization
                port:
                  number: 8083
            path: /
            pathType: Prefix
    {{- end }}
    {{- if .Values.ingress.frontendlanding }}
    - host: {{ .Values.ingress.frontendlanding }}
      http:
        paths:
          - backend:
              service:
                name: frontend-landing
                port:
                  number: 8084
            path: /
            pathType: Prefix
    {{- end }}
    {{- if .Values.ingress.flowable }}
    - host: {{ .Values.ingress.flowable }}
      http:
        paths:
          - path: /flowable-work
            pathType: Prefix
            backend:
              service:
                name: deps-scotia-flowable
                port:
                  number: 8080
          - path: /flowable-control
            pathType: Prefix
            backend:
              service:
                name: deps-scotia-flowable
                port:
                  number: 8080
          - path: /cases
            pathType: Prefix
            backend:
              service:
                name: flowable-backend
                port:
                  number: 5000
          - path: /send
            pathType: Prefix
            backend:
              service:
                name: flowable-backend
                port:
                  number: 5000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: roundcube
                port:
                  number: 8080
  {{- end }}
{{- end }}
