{{- if .Values.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Values.route.metadata.name }}
  labels: {{ .Values.route.metadata.labels }}
  annotations:
    {{- range $key, $value := .Values.route.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  host: {{ .Values.route.spec.host }}
  port:
    targetPort: {{ .Values.route.spec.port.targetPort }}
  to:
    kind: Service
    name: {{ .Values.route.spec.to.name }}
    weight: 100
  wildcardPolicy: None
  tls:
    termination: {{ .Values.route.spec.tls.termination }}
    insecureEdgeTerminationPolicy: {{ .Values.route.spec.tls.insecureEdgeTerminationPolicy }}
{{- end }}
