# Default values for deps-nginx.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Secrets declaration
# Precreate them before deploy
# kubectl create secret generic upstream-auth-url --from-literal=upstream-auth-url=<KEYCLOAK_URL>

secrets:
  ssl_certificate:
    secretName: nginx-ssl-certificate
  upstream_auth_url:
    secretName: upstream-auth-url
  csp_permitted_origin:
    secretName: csp-permitted-origin
  auth_uri:
    secretName: auth-uri
  frontend_secret:
    secretName: frontend-secret
  common_secret:
    secretName: common-secret
  deps_nginx:
    secretName: deps-nginx

helm_logs_job:
  serviceAccountName: gitlab-ci
  image:
    path: "/base/kubernetes-helm"
    pullPolicy: IfNotPresent
    tag: "0.1.1"
  resources: {}

replicaCount: 1

registry: ""
env: ""

dnsmasq_image:
  path: "/base/go-dnsmasq-alpine3-19-7"
  tag: "release-1.0.7"
  pullPolicy: IfNotPresent

image:
  path: "/deps-dev-x01/deps-nginx"
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: artifactory

podAnnotations: {}

service:
  type: ClusterIP
  port: 443
  nodeport:
    enabled: false
    port: 32000
    targetPort: 80
    servicePort: 80

dnsService:
  name: deps-dns
  dnsHost: kube-dns.kube-system.svc.cluster.local

ingress:
  redirect_to_https: false
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 100m
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  host: ""
  hostlabelingtool: ""
  frontendcustomization: ""
  comparison: true
  flowable: ""
  frontendlanding: ""
  tls:
  - secretName: tls-secret-ingress
    hosts:
    - ""

ingress_route:
  redirect_to_https: ""
  enabled: false
  name: nginx-tls-ingress
  namespace: ""
  nameOption: nginx-tls
  secretName: tls-secret-ingress
  minVersion: VersionTLS12
  maxVersion: VersionTLS13
  serviceNginx: nginx
  serviceRabbitmq: rabbitmq
  host: ""

route:
  enabled: false
  metadata:
    name: ""
  spec:
    host: ""
    port:
      targetPort: ""
    to:
      kind: Service
      name: ""
    tls:
      termination: edge
      insecureEdgeTerminationPolicy: Redirect

# Change to disable if need deploy to openshift
include_dns:
  enabled: true

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 100m
    memory: 100Mi
  requests:
    cpu: 80m
    memory: 55Mi

nodeSelector: {}

tolerations: []

affinity: {}

# Please keep README.md updated according to settings
nginx_settings:
  NGINX_PORT: '8080'
  NGINX_UNSECURE_PORT: '8088'
  NGINX_WORKERS: '4'
  NGINX_CONNECTIONS: '2048'
  NGINX_CORS_ALLOW_ORIGIN: '~^https:\/\/.*\.epam\.com.*'
  SSL:
    enabled: true
  NGINX_SSL: 'ssl'
  UPSTREAM_FRONTEND_URL: 'http://frontend:8000'
  UPSTREAM_BACKEND_URL: 'http://backend:8000'
  UPSTREAM_CORLEONE_URL: 'http://corleone:8000'
  UPSTREAM_OCR_URL: 'http://ocr:8000'
  UPSTREAM_OMR_URL: 'http://omr:8000'
  UPSTREAM_PREPROCESS_URL: 'http://preprocess-api:8000'
  UPSTREAM_TABLES_URL: 'http://tables:8000'
  UPSTREAM_STORAGE_URL: 'http://file-storage-nginx:8000'
  UPSTREAM_PLAYGROUND_URL: 'http://playground:8888'
  UPSTREAM_COMPARISON_URL: 'http://deps-comparison-api:8000'
  UPSTREAM_CONTRACTS_URL: 'http://contracts:8000'
  UPSTREAM_VALIDATION_URL: 'http://validation:8005'
  UPSTREAM_IMAGE_PREPROCESS_URL: 'http://image-preprocess:8000'
  UPSTREAM_PARSED_DATA_URL: 'http://parsed-data:8000'
  UPSTREAM_NAMED_ENTITY_RECOGNITION_URL: 'http://named-entity-recognition:8000'
  UPSTREAM_PRESALES_URL: 'http://presales:8000'
  UPSTREAM_UNIFIER_URL: 'http://unifier:8000'
  UPSTREAM_DOCUMENT_TYPE_URL: 'http://document-type:8000'
  UPSTREAM_TEMPLATE_URL: 'http://template:8000'
  UPSTREAM_EXTRACTION_URL: 'http://extraction:8000'
  UPSTREAM_WORKFLOW_MANAGER_URL: 'http://workflow-manager:8000'
  UPSTREAM_API_GATEWAY_URL: 'http://api-gateway:8000'
  UPSTREAM_RESULT_EXPORTING_URL: 'http://result-exporting:8000'
  UPSTREAM_PARSING_URL: 'http://parsing:8000'
  UPSTREAM_OUTPUT_EXPORTING_URL: 'http://output-exporting:8000'
  UPSTREAM_PROTOTYPE_URL: 'http://prototype:8000'
  UPSTREAM_PROMPTER_URL: 'http://prompter:8000'
  UPSTREAM_ENRICHMENT_URL: 'http://enrichment:8000'
  UPSTREAM_HIGH_SPARROW_URL: 'http://high-sparrow:8000'
  UPSTREAM_AI_FUSION_URL: 'http://ai-fusion:8000'
  UPSTREAM_CLOUD_NATIVE_EXTRACTION_URL: 'http://cloud-native-extraction:8000'
  UPSTREAM_GROUPS_URL: 'http://groups:8000'
  UPSTREAM_CLASSIFICATION_URL: 'http://classification:8000'
  UPSTREAM_FILE_URL: 'http://file:8000'
  UPSTREAM_FILES_BATCH_URL: 'http://files-batch:8000'
  UPSTREAM_EVENT_RELAY_URL: 'http://event-relay:8000'
  UPSTREAM_AGENTIC_AI_URL: 'http://agentic-ai:8000'

  DNS_RESOLVER_URL: '127.0.0.11:53'
  AUTHORIZATION_ENABLED: 'true'
  API_KEY_AUTH: 'true'
  UPSTREAM_AUTHORIZATION_URL: 'http://iam:8000'
  AUTHORIZATION_URI: '/api/iam/v1/authorize'
  CSP_ACTIVE: '1'
  HEALTHCHECK:
    enabled: true
  MODSECURITY: 'off'
  CLIENT_MAX_BODY_SIZE: '1000m'
  PROXY_READ_TIMEOUT: '600'
  PROXY_SEND_TIMEOUT: '600'
  UWSGI_READ_TIMEOUT: '600'
  UWSGI_SEND_TIMEOUT: '600'
  STORAGE_PROXY_BUFFERING: 'off'

helm:
  helm_logs_job_enabled: false

csi:
  csi_default_name: deps-nginx
  vault_namespace: 'k8s-dev'
  roleName: 'k8s-dev'
  vaultKubernetesMountPath: 'kubernetes-dev'
### Change csi_default_name

secrets_location:
  secrets_default_path: "/mnt/secrets-store"

service_account:
  serviceAccountName: 'deps-develop'

secret_project_id:
  id: ""

azure_kv_settings:
  keyvaultName: ""
  tenantId: ""
  userAssignedIdentityID: ""
  resourceGroup: ""
  subscriptionId: ""

vault_settings:
  enabled: false
  hashicorp_vault: false
  azure_key_vault: false
  gcp_secret_manager: false
  aws_secret_manager: false
  aws_secret_manager_region: ''

vault_enabled:
  env:
  - name: FEATURE_DOCUMENT_UPLOAD
    valueFrom:
      secretKeyRef:
        name: deps-nginx
        key: feature-document-upload
  - name: FEATURE_DOCUMENT_DELETE
    valueFrom:
      secretKeyRef:
        name: deps-nginx
        key: feature-document-delete
  - name: FEATURE_MODEL_MANAGEMENT
    valueFrom:
      secretKeyRef:
        name: deps-nginx
        key: feature-model-management
  - name: FEATURE_DOCUMENT_CHANGE_TYPE
    valueFrom:
      secretKeyRef:
        name: deps-nginx
        key: feature-document-change-type
  - name: FEATURE_RUN_PIPELINE
    valueFrom:
      secretKeyRef:
        name: deps-nginx
        key: feature-run-pipeline
  - name: NGINX_SSL_CERT
    valueFrom:
      secretKeyRef:
        name: deps-nginx
        key: tls.crt
  - name: NGINX_SSL_CERT_KEY
    valueFrom:
      secretKeyRef:
        name: deps-nginx
        key: tls.key
  - name: UPSTREAM_AUTH_URL
    valueFrom:
      secretKeyRef:
        name: deps-nginx
        key: upstream-auth-url
  - name: AUTH_ENABLED
    valueFrom:
      secretKeyRef:
        name: deps-nginx
        key: auth-enabled
  - name: CSP_PERMITTED_ORIGIN
    valueFrom:
      secretKeyRef:
        name: deps-nginx
        key: csp-permitted-origin
  - name: AUTH_URI
    valueFrom:
      secretKeyRef:
        name: deps-nginx
        key: auth-uri

vault_disabled:
  env:
  - name: FEATURE_DOCUMENT_UPLOAD
    valueFrom:
      secretKeyRef:
        name: feature-flags
        key: feature-document-upload
  - name: FEATURE_DOCUMENT_DELETE
    valueFrom:
      secretKeyRef:
        name: feature-flags
        key: feature-document-delete
  - name: FEATURE_MODEL_MANAGEMENT
    valueFrom:
      secretKeyRef:
        name: feature-flags
        key: feature-model-management
  - name: FEATURE_DOCUMENT_CHANGE_TYPE
    valueFrom:
      secretKeyRef:
        name: feature-flags
        key: feature-document-change-type
  - name: FEATURE_RUN_PIPELINE
    valueFrom:
      secretKeyRef:
        name: feature-flags
        key: feature-run-pipeline
  - name: NGINX_SSL_CERT
    valueFrom:
      secretKeyRef:
        name: nginx-ssl-certificate
        key: certificate
  - name: NGINX_SSL_CERT_KEY
    valueFrom:
      secretKeyRef:
        name: nginx-ssl-certificate
        key: certificate-key
  - name: UPSTREAM_AUTH_URL
    valueFrom:
      secretKeyRef:
        name: upstream-auth-url
        key: upstream-auth-url
  - name: AUTH_ENABLED
    valueFrom:
      secretKeyRef:
        name: common-secret
        key: auth-enabled
  - name: CSP_PERMITTED_ORIGIN
    valueFrom:
      secretKeyRef:
        name: csp-permitted-origin
        key: csp-permitted-origin
  - name: AUTH_URI
    valueFrom:
      secretKeyRef:
        name: auth-uri
        key: auth-uri
