image:
  path: "/deps-platform/deps-nginx"

resources:

# Change to disable if need deploy to openshift
include_dns:
  enabled: true

ingress:
  enabled: true
  host: ""
  hostlabelingtool: ""
  tls:
    - secretName: tls-secret-ingress
      hosts:
        - ""

helm: 
  helm_logs_job_enabled: true
  
csi:
  vault_namespace: 'k8s-demo'
  roleName: 'k8s-demo'
  vaultKubernetesMountPath: 'kubernetes-demo'

service_account:
  serviceAccountName: 'deps-demo'
