image:
  path: "/deps-platform/deps-nginx"

resources:
  limits:
    cpu:
    memory:
  requests:
    cpu:
    memory:

# Change to disable if need deploy to openshift
include_dns:
  enabled: true

ingress:
  enabled: true
  host: ""
  tls:
    - secretName: tls-secret-ingress
      hosts:
        - ""

helm: 
  helm_logs_job_enabled: true
  
csi:
  vault_namespace: 'k8s-ds'
  roleName: 'k8s-ds'
  vaultKubernetesMountPath: 'kubernetes-ds'

service_account:
  serviceAccountName: 'deps-ds'
